# Generated by Django 6.0.5 on 2026-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appointment_created_at_auditlog_doctorprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
