# Generated by Django 6.0.5 on 2026-05-23 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_options_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reușită'), ('LOGIN_FAILED', 'Autentificare eșuată'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Înregistrare cont nou'), ('APPT_CREATED', 'Programare creată'), ('APPT_APPROVED', 'Programare aprobată'), ('APPT_DELETED', 'Programare ștearsă'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Rețetă creată'), ('PASSWORD_CHANGED', 'Parolă schimbată'), ('PATIENT_RECORD_VIEWED', 'Fișă pacient vizualizată'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbată')], max_length=50),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('medication', models.TextField(help_text='Un medicament per linie')),
                ('instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='accounts.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
