# Generated by Django 6.0.5 on 2026-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctorprofile_avatar_alter_prescription_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reușită'), ('LOGIN_FAILED', 'Autentificare eșuată'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Înregistrare cont nou'), ('APPT_CREATED', 'Programare creată'), ('APPT_APPROVED', 'Programare aprobată'), ('APPT_COMPLETED', 'Consultație finalizată'), ('APPT_DELETED', 'Programare ștearsă'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Rețetă creată'), ('PASSWORD_CHANGED', 'Parolă schimbată'), ('PATIENT_RECORD_VIEWED', 'Fișă pacient vizualizată'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbată')], max_length=50),
        ),
    ]
