# Generated by Django 6.0.5 on 2026-05-25 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appointment_is_completed_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reușită'), ('LOGIN_FAILED', 'Autentificare eșuată'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Înregistrare cont nou'), ('APPT_CREATED', 'Programare creată'), ('APPT_APPROVED', 'Programare aprobată'), ('APPT_COMPLETED', 'Consultație finalizată'), ('APPT_DELETED', 'Programare ștearsă'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Rețetă creată'), ('PASSWORD_CHANGED', 'Parolă schimbată'), ('PATIENT_RECORD_VIEWED', 'Fișă pacient vizualizată'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbată'), ('RATING_GIVEN', 'Evaluare acordată'), ('GDPR_EXPORT', 'Export date GDPR')], max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
