# Generated by Django 6.0.5 on 2026-06-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_appointment_beneficiary_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='beneficiary_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data nasterii beneficiar'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='beneficiary_relation',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Relatie (copil, parinte, etc.)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reusita'), ('LOGIN_FAILED', 'Autentificare esuata'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Inregistrare cont nou'), ('APPT_CREATED', 'Programare creata'), ('APPT_APPROVED', 'Programare aprobata'), ('APPT_COMPLETED', 'Consultatie finalizata'), ('APPT_DELETED', 'Programare stearsa'), ('APPT_NO_SHOW', 'Neprezentare marcata'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Reteta creata'), ('PASSWORD_CHANGED', 'Parola schimbata'), ('PATIENT_RECORD_VIEWED', 'Fisa pacient vizualizata'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbata'), ('RATING_GIVEN', 'Evaluare acordata'), ('GDPR_EXPORT', 'Export date GDPR'), ('PAYMENT_CREATED', 'Plata inregistrata'), ('CNAS_GENERATED', 'Cod CNAS generat'), ('WALLET_TOPUP', 'Wallet reincarcat'), ('CASHBACK_CREDIT', 'Cashback 5% acordat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD_ONLINE', 'Card online'), ('ONLINE', 'Online'), ('CNAS', 'Decontat CNAS'), ('WALLET', 'Wallet MedApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In asteptare'), ('COMPLETED', 'Finalizat'), ('FAILED', 'Esuat'), ('REFUNDED', 'Rambursat')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('TOPUP', 'Reincarcare card'), ('PAYMENT', 'Plata consultatie'), ('CASHBACK', 'Cashback 5% card online'), ('TRANSFER', 'Transfer (apartinat)'), ('REFUND', 'Rambursare')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='accounts.appointment')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
