# Generated by Django 6.0.5 on 2026-06-01 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_appointment_beneficiary_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reusita'), ('LOGIN_FAILED', 'Autentificare esuata'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Inregistrare cont nou'), ('APPT_CREATED', 'Programare creata'), ('APPT_APPROVED', 'Programare aprobata'), ('APPT_COMPLETED', 'Consultatie finalizata'), ('APPT_DELETED', 'Programare stearsa'), ('APPT_NO_SHOW', 'Neprezentare marcata'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Reteta creata'), ('PASSWORD_CHANGED', 'Parola schimbata'), ('PATIENT_RECORD_VIEWED', 'Fisa pacient vizualizata'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbata'), ('RATING_GIVEN', 'Evaluare acordata'), ('GDPR_EXPORT', 'Export date GDPR'), ('PAYMENT_CREATED', 'Plata inregistrata'), ('CNAS_GENERATED', 'Cod CNAS generat'), ('WALLET_TOPUP', 'Wallet reincarcat'), ('CASHBACK_CREDIT', 'Cashback 5% acordat'), ('SOFT_BAN', 'Blocare temporara 10 min'), ('HARD_BAN', 'Blocare permanenta cont/IP'), ('BAN_REVOKED', 'Ban revocat de admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_soft_banned', models.BooleanField(default=False)),
                ('soft_ban_until', models.DateTimeField(blank=True, null=True)),
                ('is_hard_banned', models.BooleanField(default=False)),
                ('hard_ban_reason', models.CharField(blank=True, default='', max_length=200)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
