# Generated by Django 6.0.5 on 2026-06-04 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_auditlog_action_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reusita'), ('LOGIN_FAILED', 'Autentificare esuata'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Inregistrare cont nou'), ('APPT_CREATED', 'Programare creata'), ('APPT_APPROVED', 'Programare aprobata'), ('APPT_COMPLETED', 'Consultatie finalizata'), ('APPT_DELETED', 'Programare stearsa'), ('APPT_NO_SHOW', 'Neprezentare marcata'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Reteta creata'), ('PASSWORD_CHANGED', 'Parola schimbata'), ('PATIENT_RECORD_VIEWED', 'Fisa pacient vizualizata'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbata'), ('RATING_GIVEN', 'Evaluare acordata'), ('GDPR_EXPORT', 'Export date GDPR'), ('PAYMENT_CREATED', 'Plata inregistrata'), ('CNAS_GENERATED', 'Cod CNAS generat'), ('WALLET_TOPUP', 'Wallet reincarcat'), ('CASHBACK_CREDIT', 'Cashback 5% acordat'), ('SOFT_BAN', 'Blocare temporara 10 min'), ('HARD_BAN', 'Blocare permanenta cont/IP'), ('BAN_REVOKED', 'Ban revocat de admin'), ('TWO_FA_SENT', 'Cod 2FA trimis'), ('TWO_FA_SUCCESS', 'Autentificare 2FA reusita'), ('TWO_FA_FAILED', 'Cod 2FA gresit')], max_length=50),
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
