# Generated by Django 6.0.5 on 2026-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_auditlog_action_twofactorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_seen',
            field=models.BooleanField(default=False, verbose_name='Notificare vazuta'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Autentificare reusita'), ('LOGIN_FAILED', 'Autentificare esuata'), ('LOGOUT', 'Deconectare'), ('REGISTER', 'Inregistrare cont nou'), ('APPT_CREATED', 'Programare creata'), ('APPT_APPROVED', 'Programare aprobata'), ('APPT_COMPLETED', 'Consultatie finalizata'), ('APPT_DELETED', 'Programare stearsa'), ('APPT_NO_SHOW', 'Neprezentare marcata'), ('PROFILE_UPDATED', 'Profil actualizat'), ('PRESCRIPTION_CREATED', 'Reteta creata'), ('PASSWORD_CHANGED', 'Parola schimbata'), ('PATIENT_RECORD_VIEWED', 'Fisa pacient vizualizata'), ('AVAILABILITY_CHANGED', 'Disponibilitate schimbata'), ('RATING_GIVEN', 'Evaluare acordata'), ('GDPR_EXPORT', 'Export date GDPR'), ('PAYMENT_CREATED', 'Plata inregistrata'), ('CNAS_GENERATED', 'Cod CNAS generat'), ('WALLET_TOPUP', 'Wallet reincarcat'), ('CASHBACK_CREDIT', 'Cashback 5% acordat'), ('SOFT_BAN', 'Blocare temporara 10 min'), ('HARD_BAN', 'Blocare permanenta cont/IP'), ('BAN_REVOKED', 'Ban revocat de admin'), ('TWO_FA_SENT', 'Cod 2FA trimis'), ('TWO_FA_SUCCESS', 'Autentificare 2FA reusita'), ('TWO_FA_FAILED', 'Cod 2FA gresit'), ('NOTIF_DISMISSED', 'Notificare inchisa')], max_length=50),
        ),
    ]
